site_name: ISARIC 3.0 Rapid Pipeline Documentation
nav: 
  - Home: index.md
  - Installation: installation.md
  - Getting Started: getting_started.md
  - User Guide:
      - Data Preparation: data_preparation.md
      - Running the Pipeline: running_the_pipeline.md
      - Interpreting Results: interpreting_results.md
theme: readthedocs