site_name: ISARIC 3.0 Rapid Pipeline Documentation
nav: 
  - Getting Started:
    - Home: index.md
    - Why RAPID?: why_rapid.md
    - Installation: installation.md
    - Quick Start Guide: getting_started.md
  - User Guide:
      - Running the Pipeline: running_the_pipeline.md
  - Extra:
      - Development: getting_started_development.md
theme: readthedocs