[build-system]
requires = ["setuptools>=65.0"]
build-backend = "setuptools.build_meta"

[project]
name = "isaric"
version = "0.1.0"
description = "Modular package for implementing the RAPID methodology: reproducible analytics for predictive modeling, inference, and data preprocessing in clinical research"
dependencies = [
    "nbformat == 5.10.4",
    "pandas==2.3.3",
    "numpy==2.3.5",
    "formulaic==1.2.1",
    "scikit-learn==1.7.2",
    "lifelines==0.30.0",
    "statsmodels == 0.14.5",
    "matplotlib==3.10.7",
	"seaborn==0.13.2",
    "upsetplot==0.9.0",
    plotly==5.16.0,
]

authors = [
    { name = "ISARIC HUB SA" }
]
license = { text = "MIT" }

[tool.setuptools.packages.find]
where = ["src"]
namespaces = true
